# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2ef5e30d5945dcf61b15b796a97d8b532a82d844f020bdaa58e7a197cb6513dc571a9b689ad5593e4cff3e6a87300c650e70eb94c720697c0cdc2aad2a0d9ac4

test:
  secret_key_base: cb44e00f8cb64ed3693b47f224b609f57905d98afbc4f1e6c72a5c10f5023de726c08b1e28c250208a1ae3a38cd7ef02c1f39c29c81c1cd7f522f18b40a4752c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
